import { galleryEntries, buildPlayerCard, RARITY_ORDER, formatHeight } from '../src/engine/playerCard';
const g = galleryEntries();
console.log(`gallery entries: ${g.length}`);
const hist: Record<string, number> = {};
for (const e of g) hist[e.rarity] = (hist[e.rarity] ?? 0) + 1;
console.log('rarity histogram:', RARITY_ORDER.map(r => `${r} ${hist[r] ?? 0}`).join('  '));
console.log('top 8:', g.slice(0, 8).map(e => `${e.name} [${e.rarity}/${e.bestTier}]`).join(', '));
console.log('\n--- LeBron James card ---');
const c = buildPlayerCard('LeBron James')!;
console.log(`${c.name} · ${c.naturalPos} · ${c.spanRange} · ${c.bestTier} (${c.rarity}) · ${c.allStar}x AS`);
console.log(`bio: ${c.heightIn ? formatHeight(c.heightIn) : '?'} · ${c.weightLbs ?? '?'} lb · ath ${c.athleticism?.toFixed(0) ?? '?'}`);
console.log(`career: ${c.career ? `${c.career.ppg}/${c.career.rpg}/${c.career.apg} ${(c.career.fgPct*100).toFixed(1)}FG ${(c.career.threePct*100).toFixed(1)}3P ${c.career.games}g` : 'none'}`);
console.log(`${c.rows.length} span rows. first:`);
const r = c.rows[0];
console.log(`  ${r.span.spanLabel} ${r.span.primaryPosition} TAL ${r.tal} ${r.tier} | O ${r.oGrade} D ${r.dGrade} OPOR ${r.oporGrade} DPOR ${r.dporGrade} SPC ${r.spacing}(${r.spacingTier}) DUR ${r.durability}(${r.durabilityTier}) PO ${r.playoffTier ?? '—'}`);
console.log(`  archetype ${r.archetype} / role ${r.role}`);
console.log(`  box: ${r.span.box.ppg}/${r.span.box.rpg}/${r.span.box.apg} ${r.span.box.spg}s ${r.span.box.bpg}b`);
console.log(`  evidence +: ${r.evidence.evidence.map(e=>e.text.slice(0,50)).join(' | ')}`);
console.log(`  evidence -: ${r.evidence.counterEvidence.map(e=>e.text.slice(0,50)).join(' | ')}`);
// a common + missing-bio player
const common = g.find(e => e.rarity === 'common')!;
const cc = buildPlayerCard(common.name)!;
console.log(`\n--- ${cc.name} (common) --- bio: ${cc.heightIn?formatHeight(cc.heightIn):'?'} ${cc.weightLbs??'?'}lb ath ${cc.athleticism?.toFixed(0)??'?'} career ${cc.career?'yes':'NONE'} rows ${cc.rows.length}`);
