/**
 * Reads every player JSON file in the player-data source folder, filters to real
 * rotation players, emits every qualifying window (the drafter chooses which stretch of
 * a career to draft, not a pre-picked few), derives box stats, classifies offensive
 * archetype and defensive role via a documented rules-based heuristic (no qualitative data
 * exists in the source, so this is a transparent approximation), and writes the result to
 * src/data/generatedPlayers.ts. Players already present in the hand-curated players.ts are
 * skipped entirely — see scripts/expandCuratedSpans.ts for how their extra windows are
 * generated instead, inheriting hand judgment rather than the rules-based classifier.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { curatedPlayers } from '../src/data/players';
import { normalizePlayerName } from '../src/data/schema';
import type { PlayerSpan } from '../src/data/schema';
import {
  type RawPlayer,
  type RawSpan,
  spanQualifies,
  playerQualifies,
  deriveBox,
  classifyOffense,
  classifyDefense,
  spanLabelFor,
  computePositionBreakdown,
} from './lib/rawPlayerData';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_DIR = 'C:\\Users\\Eryks\\Desktop\\player-data';
const JSON_FILE = path.resolve(__dirname, '../src/data/generatedPlayers.json');
const OUT_FILE = path.resolve(__dirname, '../src/data/generatedPlayers.ts');

// --- Span selection: every qualifying window is offered, not a representative subset — the
// drafter chooses which stretch of a career to draft, the same way the in-person game worked. ---
function selectSpans(allSpans: RawSpan[]): RawSpan[] {
  return allSpans.filter(spanQualifies).sort((a, b) => a.startSeasonEnd - b.startSeasonEnd);
}

// --- Main ---
const existingNames = new Set(curatedPlayers.map((p) => normalizePlayerName(p.playerName)));
const files = fs.readdirSync(DATA_DIR).filter((f) => f.endsWith('.json'));

const result: PlayerSpan[] = [];
let skippedCurated = 0;
let skippedQuality = 0;
let skippedNoSpans = 0;
let skippedNoPosition = 0;
const usedIds = new Set<string>();

for (const file of files) {
  let raw: RawPlayer;
  try {
    raw = JSON.parse(fs.readFileSync(path.join(DATA_DIR, file), 'utf8'));
  } catch {
    continue;
  }
  if (!raw.name || !raw.spans || raw.spans.length === 0) {
    skippedNoSpans++;
    continue;
  }
  if (existingNames.has(normalizePlayerName(raw.name))) {
    skippedCurated++;
    continue;
  }
  if (!playerQualifies(raw.spans)) {
    skippedQuality++;
    continue;
  }

  const chosen = selectSpans(raw.spans);
  if (chosen.length === 0) {
    skippedQuality++;
    continue;
  }

  for (const span of chosen) {
    const { primary: position, secondary: secondaryPositions } = computePositionBreakdown(span.seasons, span);
    if (!position) {
      skippedNoPosition++;
      continue;
    }
    const box = deriveBox(span);
    const archetype = classifyOffense(position, box);
    const defensiveRole = classifyDefense(position, box);
    let id = `${raw.id}-${span.startSeasonEnd}-${span.endSeasonEnd}`;
    while (usedIds.has(id)) id += 'x';
    usedIds.add(id);

    result.push({
      id,
      playerName: raw.name,
      spanLabel: spanLabelFor(span),
      primaryPosition: position,
      secondaryPositions,
      fga: Math.round(box.fga * 10) / 10,
      box: {
        ppg: Math.round(box.ppg * 10) / 10,
        rpg: Math.round(box.rpg * 10) / 10,
        apg: Math.round(box.apg * 10) / 10,
        spg: Math.round(box.spg * 10) / 10,
        bpg: Math.round(box.bpg * 10) / 10,
        fgPct: Math.round(box.fgPct * 1000) / 1000,
        threePct: Math.round(box.threePct * 1000) / 1000,
        threePA: Math.round(box.threePA * 10) / 10,
        ftPct: Math.round(box.ftPct * 1000) / 1000,
        tsPct: Math.round(box.tsPct * 1000) / 1000,
      },
      offensiveArchetype: archetype,
      defensiveRole,
    });
  }
}

console.log(`Files scanned: ${files.length}`);
console.log(`Skipped (already curated): ${skippedCurated}`);
console.log(`Skipped (quality filter): ${skippedQuality}`);
console.log(`Skipped (no spans/parse error): ${skippedNoSpans}`);
console.log(`Skipped (no position data): ${skippedNoPosition}`);
console.log(`Unique players included: ${new Set(result.map((p) => p.playerName)).size}`);
console.log(`Total generated entries: ${result.length}`);

// Data lives in a .json file and the .ts file just re-exports it typed — at 12,000+ entries
// a literal array expression overflows TypeScript's type checker (TS2590), since it tries to
// infer a precise union type per object rather than just trusting the PlayerSpan[] annotation.
fs.writeFileSync(JSON_FILE, JSON.stringify(result, null, 2) + '\n');
const wrapper = `// Auto-generated by scripts/generatePlayers.ts — do not hand-edit.
// Regenerate by re-running that script against the player-data source folder.
import type { PlayerSpan } from './schema';
import data from './generatedPlayers.json';

export const generatedPlayers: PlayerSpan[] = data as PlayerSpan[];
`;
fs.writeFileSync(OUT_FILE, wrapper);
console.log(`Wrote ${JSON_FILE} and ${OUT_FILE}`);
