// Auto-generated by scripts/expandCuratedSpans.ts — do not hand-edit.
// Regenerate by re-running that script. See its header comment for what this is and why
// it exists separately from the hand-typed rows in players.ts.
import type { PlayerSpan } from './schema';
import data from './curatedExpandedSpans.json';

export const curatedExpandedSpans: PlayerSpan[] = data as PlayerSpan[];
