// Auto-generated by scripts/buildDraftPool.ts — do not hand-edit.
// Regenerate by re-running that script after generatePlayers.ts / expandCuratedSpans.ts.
// See that script's header comment for what the pool is and why it's precomputed rather
// than filtered from the full dataset in the browser (bundle size: the full archive is
// ~14,000 entries; the pool is ~300 players' worth).
import type { PlayerSpan } from './schema';
import data from './draftPool.json';
import { auditedPrimaryDefensiveRole, buildRoleFitContext } from '../engine/roleFitShadow';

// The JSON is a precomputed build artifact, but position corrections in players.ts must also be
// visible immediately without reselecting the entire talent-sensitive pool (a full rebuild churns
// ~1,000 borderline value-tier spans on unrelated accumulated formula drift). These tiny runtime
// parity adjustments mirror what `players.ts`'s `POSITION_OVERRIDES` / `SECONDARY_POSITION_
// ADDITIONS` already do to the full archive; the next intentional pool rebuild bakes them into JSON.
function applyRuntimeParity(span: PlayerSpan): PlayerSpan {
  // Olynyk — real C/PF, only his PF eligibility changed.
  if (span.playerName === 'Kelly Olynyk' && span.primaryPosition !== 'PF' && !span.secondaryPositions.includes('PF')) {
    return { ...span, secondaryPositions: [...span.secondaryPositions, 'PF'] };
  }
  // Kirilenko 2003-05 — one-span SF-primary classifier artifact (see `POSITION_OVERRIDES` in
  // players.ts). As PF it dodged the SF elite-defense tier cap and read Greatest peak.
  if (span.playerName === 'Andrei Kirilenko' && span.spanLabel === '2003-05' && span.primaryPosition === 'PF') {
    return { ...span, primaryPosition: 'SF', secondaryPositions: ['PF'] };
  }
  if (
    span.playerName === 'Pau Gasol' &&
    ['2007-09', '2008-10', '2009-11'].includes(span.spanLabel) &&
    span.primaryPosition === 'C'
  ) {
    return { ...span, primaryPosition: 'PF', secondaryPositions: ['C'] };
  }
  // Harden 2015-onward — primary PG (see `POSITION_OVERRIDES` in players.ts).
  if (
    span.playerName === 'James Harden' &&
    ['2015-17', '2017-19', '2018-20', '2019-21'].includes(span.spanLabel) &&
    span.primaryPosition === 'SG'
  ) {
    return { ...span, primaryPosition: 'PG', secondaryPositions: ['SG'] };
  }
  // `DEFENSIVE_ROLE_OVERRIDES` parity (see players.ts) — pool JSON is precomputed, mirror until rebuild.
  if (span.playerName === 'Magic Johnson' && span.spanLabel === '1989-91' && span.defensiveRole === 'Low Activity') {
    return { ...span, defensiveRole: 'Wing Stopper' };
  }
  if (
    span.playerName === 'Stephen Curry' &&
    ['2013-15', '2014-16', '2015-17', '2016-18'].includes(span.spanLabel) &&
    span.defensiveRole === 'Low Activity'
  ) {
    return { ...span, defensiveRole: 'Chaser' };
  }
  // `SECONDARY_POSITION_ADDITIONS` parity: Draymond gains C (players.ts grants it to every span).
  if (span.playerName === 'Draymond Green' && span.primaryPosition !== 'C' && !span.secondaryPositions.includes('C')) {
    return { ...span, secondaryPositions: [...span.secondaryPositions, 'C'] };
  }
  return span;
}

const positionCorrectedPool = (data as PlayerSpan[]).map(applyRuntimeParity);
const defensiveRoleAuditContext = buildRoleFitContext(positionCorrectedPool);

/** Legacy Anchor/Mobile tags are replaced at load time by the audited physical/statistical
 * primary role. The full multi-role profile is still calculated separately by FIT. */
export const draftPool: PlayerSpan[] = positionCorrectedPool.map((span) => ({
  ...span,
  defensiveRole: auditedPrimaryDefensiveRole(span, defensiveRoleAuditContext),
}));
