// Auto-generated by scripts/buildDraftPool.ts — do not hand-edit.
// Regenerate by re-running that script after generatePlayers.ts / expandCuratedSpans.ts.
// See that script's header comment for what the pool is and why it's precomputed rather
// than filtered from the full dataset in the browser (bundle size: the full archive is
// ~14,000 entries; the pool is ~300 players' worth).
import type { PlayerSpan } from './schema';
import data from './draftPool.json';

// The JSON is a precomputed build artifact, but position corrections in players.ts must also be
// visible immediately without reselecting the entire talent-sensitive pool (a full rebuild churns
// ~1,000 borderline value-tier spans on unrelated accumulated formula drift). These tiny runtime
// parity adjustments mirror what `players.ts`'s `POSITION_OVERRIDES` / `SECONDARY_POSITION_
// ADDITIONS` already do to the full archive; the next intentional pool rebuild bakes them into JSON.
export const draftPool: PlayerSpan[] = (data as PlayerSpan[]).map((span) => {
  // Olynyk — real C/PF, only his PF eligibility changed.
  if (span.playerName === 'Kelly Olynyk' && span.primaryPosition !== 'PF' && !span.secondaryPositions.includes('PF')) {
    return { ...span, secondaryPositions: [...span.secondaryPositions, 'PF'] };
  }
  // Kirilenko 2003-05 — one-span SF-primary classifier artifact (see `POSITION_OVERRIDES` in
  // players.ts). As PF it dodged the SF elite-defense tier cap and read Greatest peak.
  if (span.playerName === 'Andrei Kirilenko' && span.spanLabel === '2003-05' && span.primaryPosition === 'PF') {
    return { ...span, primaryPosition: 'SF', secondaryPositions: ['PF'] };
  }
  return span;
});
