// Auto-generated by scripts/buildDraftPool.ts — do not hand-edit.
// Regenerate by re-running that script after generatePlayers.ts / expandCuratedSpans.ts.
// See that script's header comment for what the pool is and why it's precomputed rather
// than filtered from the full dataset in the browser (bundle size: the full archive is
// ~14,000 entries; the pool is ~300 players' worth).
import type { PlayerSpan } from './schema';
import data from './draftPool.json';

// The JSON is a precomputed build artifact, but position corrections in players.ts must also be
// visible immediately without reselecting the entire talent-sensitive pool. Olynyk is a real
// C/PF; keeping this tiny runtime parity adjustment avoids an unrelated pool-membership churn
// when only his eligibility changed. The next intentional pool rebuild will bake it into JSON.
export const draftPool: PlayerSpan[] = (data as PlayerSpan[]).map((span) =>
  span.playerName === 'Kelly Olynyk' && span.primaryPosition !== 'PF' && !span.secondaryPositions.includes('PF')
    ? { ...span, secondaryPositions: [...span.secondaryPositions, 'PF'] }
    : span,
);
