// Auto-generated by scripts/generatePlayers.ts — do not hand-edit.
// Regenerate by re-running that script against the player-data source folder.
import type { PlayerSpan } from './schema';
import data from './generatedPlayers.json';

export const generatedPlayers: PlayerSpan[] = data as PlayerSpan[];
